### ISSUE TITLE
Intermittent test failure DispatcherBlockConsumerTest.testConsumerBlockingWithUnAckedMessagesAtDispatcher

### ISSUE THREAD

**Issue by rdhabalia** [apache/incubator-pulsar#1003]
[Build](https://builds.apache.org/job/pulsar-pull-request/org.apache.pulsar$pulsar-broker/943/testReport/junit/org.apache.pulsar.client.api/DispatcherBlockConsumerTest/testConsumerBlockingWithUnAckedMessagesAtDispatcher/): 1.22.0-incubating-SNAPSHOT

```
Regression

org.apache.pulsar.client.api.DispatcherBlockConsumerTest.testConsumerBlockingWithUnAckedMessagesAtDispatcher

Error Message

expected [true] but found [false]
Stacktrace

java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at org.apache.pulsar.client.api.DispatcherBlockConsumerTest.testConsumerBlockingWithUnAckedMessagesAtDispatcher(DispatcherBlockConsumerTest.java:186)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by merlimat** [comment]
Still happening: 
https://builds.apache.org/job/pulsar-pull-request/org.apache.pulsar$pulsar-broker/1323/testReport/junit/org.apache.pulsar.client.api/DispatcherBlockConsumerTest/testConsumerBlockingWithUnAckedMessagesAtDispatcher/
