### ISSUE TITLE
Intermittent test failures in DiscoveryServiceTest.testClientServerConnectionTls

### ISSUE THREAD

**Issue by merlimat** [apache/incubator-pulsar#1081]
https://builds.apache.org/job/pulsar-master/org.apache.pulsar$pulsar-discovery-service/219/testReport/junit/org.apache.pulsar.discovery.service/DiscoveryServiceTest/testClientServerConnectionTls/

```
java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertTrue(Assert.java:44)
	at org.testng.Assert.assertTrue(Assert.java:54)
	at org.apache.pulsar.discovery.service.DiscoveryServiceTest.testClientServerConnectionTls(DiscoveryServiceTest.java:149)
```

**Comment by sijie** [comment]
This is fixed by #2406
