### ISSUE TITLE
Exception during namespace bundle split

### ISSUE THREAD

**Issue by merlimat** [apache/incubator-pulsar#1117]
This particular exception was reported. It was during an automatically initiated bundle split. 

```
2018-01-26 00:38:08,489 - ERROR - [pulsar-web-61-28:PulsarWebResource@381] - [null] Failed to validate namespace bundle netflix/prod/ns1/0x84000000_0x86000000
java.lang.IllegalArgumentException: Invalid upper boundary for bundle
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
    at org.apache.pulsar.common.naming.NamespaceBundles.validateBundle(NamespaceBundles.java:110)
    at org.apache.pulsar.broker.web.PulsarWebResource.validateNamespaceBundleRange(PulsarWebResource.java:378)
    at org.apache.pulsar.broker.web.PulsarWebResource.validateNamespaceBundleOwnership(PulsarWebResource.java:404)
    at org.apache.pulsar.broker.admin.Namespaces.splitNamespaceBundle(Namespaces.java:876)
    at sun.reflect.GeneratedMethodAccessor127.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
    at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
    at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
    at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$VoidOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:143)
    at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
    at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
    at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
    at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
    at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
```

I think that the race condition is happening since all 4 initial bundles are getting split around the same time and the bundle cache gets updated while the new bundle split is being processed. 

The result doesn't cause any particular issue, just that the bundle split fails with invalid bundle range, but the current bundle will continue to run unaffacted until the next split will take place.

**Comment by zhaijack** [comment]
will try to handle this one.

**Comment by zhaijack** [comment]
@merlimat , Would you please shed some light on how to reproduce it? Thanks.

**Comment by merlimat** [comment]
@zhaijack I think it would only reproduce when multiple brokers are doing the split. 

It probably should be be easy to reproduce by calling the split REST handler at same time for 2 (or more) bundles in a namespace. 

Example (I haven't really tried this):
 1. Create a namespace with 2 bundles (0x0000_0x7fffff and 0x800000_0xffffff) 
 2. Invoke the split in parallel on both bundles

I think the validation logic might have some flaw here. It would be good to log more info to help with the debugging. This is in `NamespaceBundles`:
```java
public void validateBundle(NamespaceBundle nsBundle) throws Exception {
        int idx = Arrays.binarySearch(partitions, nsBundle.getLowerEndpoint());
        checkArgument(idx >= 0, "Cannot find bundle in the bundles list");
        checkArgument(nsBundle.getUpperEndpoint().equals(bundles.get(idx).getUpperEndpoint()),
                "Invalid upper boundary for bundle");
    }
```

**Comment by zhaijack** [comment]
Thanks a lot.

**Comment by zhaijack** [comment]
Seems the error happens in `NamespaceService.splitAndOwnBundle()`. 
The concurrent update of Policies will cause some override to bundles value that kept in Zookeeper. And this involves at lest 2 rounds of split. 
e.g.
1. At beginning, we have 2 bundles, with partitions:[0x00000000, 0x7fffffff, 0xffffffff],

2. First round of split: We will split the 2 bundles at the same time.
  for first bundle split, the `NamespaceBundles` value that returned by `NamespaceBundleFactory.splitBundles()` would be: 
[0x00000000, 0x3fffffff, 0x7fffffff, 0xffffffff]; 
while at the same time, the `NamespaceBundles` value for second bundle split would be:
 [0x00000000, 0x7fffffff, 0xbfffffff, 0xffffffff]

3. Then the 2 split operations, whoever success `updateNamespaceBundles` last, will override the former one. 
Here if second split finally success,  the final bundles partitions would be:  [0x00000000, 0x7fffffff, 0xbfffffff, 0xffffffff];  But we thought it should be [0x00000000, 0x3fffffff, 0x7fffffff, 0xbfffffff,  0xffffffff]; 

4. Second round split:  e.g. try to split to range [0x00000000, 0x3fffffff], it will not find upper boundary 0x3fffffff in actual [0x00000000, 0x7fffffff, 0xbfffffff, 0xffffffff].
And  this will cause the error: 
``` 
java.lang.IllegalArgumentException: Invalid upper boundary for bundle
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
 ```

**Comment by merlimat** [comment]
Thanks @zhaijack for looking into. Do you think this could be solved validating the z-node version? We could have a loop of read-modify-write retrying when there are simultaneous write to the z-node, and refreshing with the latest version of the split list.

**Comment by zhaijack** [comment]
Thanks @merlimat for the suggestion, It seems work-able, will try on this way
