### ISSUE TITLE
Intermittent test failure in ResendRequestTest.testSharedSingleAckedPartitionedTopic

### ISSUE THREAD

**Issue by merlimat** [apache/incubator-pulsar#1160]
Seen in https://builds.apache.org/job/pulsar-pull-request/org.apache.pulsar$pulsar-broker/1393/testReport/junit/org.apache.pulsar.broker.service/ResendRequestTest/testSharedSingleAckedPartitionedTopic/

```
Error Message

expected [10] but found [9]

Stacktrace

java.lang.AssertionError: expected [10] but found [9]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertEqualsImpl(Assert.java:137)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:652)
	at org.testng.Assert.assertEquals(Assert.java:662)
	at org.apache.pulsar.broker.service.ResendRequestTest.testSharedSingleAckedPartitionedTopic(ResendRequestTest.java:558)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by sijie** [comment]
This was fixed by #1952
