### ISSUE TITLE
Website is not updated due to a build error

### ISSUE THREAD

**Issue by maskit** [apache/incubator-pulsar#1412]
Our website has not been updated since Mar 13.

From a build log:
```
scripts/python-doc-gen.sh
Collecting pulsar-client
  Downloading pulsar_client-1.22.0-cp27-cp27mu-manylinux1_x86_64.whl (15.7MB)
Installing collected packages: pulsar-client
Successfully installed pulsar-client-1.22.0
You are using pip version 9.0.1, however version 9.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Traceback (most recent call last):
  File "/usr/local/bin/pdoc", line 472, in <module>
    module = imp.load_source('__pdoc_file_module__', fp, f)
  File "/pulsar/pulsar-client-cpp/python/pulsar.py", line 106, in <module>
    from functions.function import Function
ImportError: No module named functions.function
mv: cannot stat '/pulsar/site/api/python/pulsar.m.html': No such file or directory
Makefile:80: recipe for target 'python_doc_gen' failed
make: *** [python_doc_gen] Error 1
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

**Comment by maskit** [comment]
The python issue was fixed, but got another error.

```
Required ruby-2.3.1 is not installed.
To install do: 'rvm install "ruby-2.3.1"'
Required ruby-2.3.1 is not installed.
Could not determine which Ruby to use; . should contain .rvmrc or .versions.conf or .ruby-version or .rbfu-version or .rbenv-version, or an appropriate line in Gemfile.
Run `rvm help` to see usage information
```

**Comment by maskit** [comment]
#1436 made progress, but got another error.
```
Using /usr/local/rvm/gems/ruby-2.3.1
gem install --user-install bundler \
	--no-rdoc \
	--no-ri
WARNING:  You don't have /root/.gem/ruby/2.3.0/bin in your PATH,
	  gem executables will not run.
GemWrappers: Can not wrap missing file: bundle
GemWrappers: Can not wrap missing file: bundler
Successfully installed bundler-1.16.1
1 gem installed
NOKOGIRI_USE_SYSTEM_LIBRARIES=true bundle install \
	--path vendor/bundle
/bin/sh: 1: bundle: not found
Makefile:44: recipe for target 'ruby_setup' failed
```
