### ISSUE TITLE
java.lang.IllegalArgumentException on refreshing stats

### ISSUE THREAD

**Issue by sijie** [apache/incubator-pulsar#1510]
Found following stacktrace when running `AdminApiTest#partitionedTopics`

```
00:55:33.359 [bookkeeper-ml-scheduler-OrderedScheduler-12-0:org.apache.bookkeeper.common.util.SafeRunnable@38] ERROR org.apache.bookkeeper.common.util.SafeRunnable - Unexpected throwable caught
java.lang.IllegalArgumentException: null
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:108) ~[guava-20.0.jar:?]
        at org.apache.bookkeeper.mledger.util.Rate.calculateRate(Rate.java:60) ~[managed-ledger-2.0.0-incubating-SNAPSHOT.jar:2.0.0-incubating-SNAPSHOT]
        at org.apache.bookkeeper.mledger.impl.ManagedLedgerFactoryMBeanImpl.refreshStats(ManagedLedgerFactoryMBeanImpl.java:41) ~[managed-ledger-2.0.0-incubating-SNAPSHOT.jar:2.0.0-incubating-SNAPSHOT]
        at org.apache.bookkeeper.mledger.impl.ManagedLedgerFactoryImpl.refreshStats(ManagedLedgerFactoryImpl.java:147) ~[managed-ledger-2.0.0-incubating-SNAPSHOT.jar:2.0.0-incubating-SNAPSHOT]
        at org.apache.bookkeeper.mledger.impl.ManagedLedgerFactoryImpl.lambda$new$2(ManagedLedgerFactoryImpl.java:140) ~[managed-ledger-2.0.0-incubating-SNAPSHOT.jar:2.0.0-incubating-SNAPSHOT]
        at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36) [bookkeeper-server-shaded-4.7.0-SNAPSHOT.jar:4.7.0-SNAPSHOT]
        at org.apache.bookkeeper.shaded.com.google.common.util.concurrent.MoreExecutors$ScheduledListeningDecorator$NeverSuccessfulListenableFutureTask.run(MoreExecutors.java:587) [bookkeeper-server-shaded-4.7.0-SNAPSHOT.jar:4.7.0-SNAPSHOT]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_144]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_144]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_144]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_144]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.21.Final.jar:4.1.21.Final]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
```

**Comment by merlimat** [comment]
Already fixed
