### ISSUE TITLE
JNI error while trying to execute bin/pulsar standalone

### ISSUE THREAD

**Issue by turboT4** [apache/incubator-pulsar#1822]
Hey guys,

I'm new to Pulsar and just downloaded the latest version, tried to execute it and got this error.

`Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/pulsar/client/admin/PulsarAdminException
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: org.apache.pulsar.client.admin.PulsarAdminException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
`

I have no clue why this is happening, hope you guys can shed some light on it.

**Comment by merlimat** [comment]
Hi @turboT4, can you specify which pulsar version and which environment OS / Java version?

**Comment by turboT4** [comment]
Thanks for the reply @merlimat , I'm trying to run Pulsar on macOS Sierra and Java version 1.8.0_121.

**Comment by sijie** [comment]
@turboT4 is this issue resolved at your side?

**Comment by sijie** [comment]
Seems there is no activities here. Closing this issue for now. @turboT4 if this happens again, feel free to report back.
