### ISSUE TITLE
Intermittent failure in integration test TestS3Offload.testPublishOffloadAndConsumeViaCLI

### ISSUE THREAD

**Issue by merlimat** [apache/incubator-pulsar#1916]
https://builds.apache.org/job/pulsar_precommit_integrationtests/1859/testReport/junit/org.apache.pulsar.tests.integration/TestS3Offload/testPublishOffloadAndConsumeViaCLI/

```
Error Message

org.apache.bookkeeper.mledger.ManagedLedgerException: Not enough non-faulty bookies available

Stacktrace

org.apache.pulsar.client.api.PulsarClientException$BrokerPersistenceException: org.apache.bookkeeper.mledger.ManagedLedgerException: Not enough non-faulty bookies available
	at org.apache.pulsar.client.impl.ClientCnx.getPulsarClientException(ClientCnx.java:747)
	at org.apache.pulsar.client.impl.ClientCnx.handleError(ClientCnx.java:497)
	at org.apache.pulsar.shade.org.apache.pulsar.common.api.PulsarDecoder.channelRead(PulsarDecoder.java:154)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at org.apache.pulsar.shade.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at org.apache.pulsar.shade.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at org.apache.pulsar.shade.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1414)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at org.apache.pulsar.shade.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:945)
	at org.apache.pulsar.shade.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:146)
	at org.apache.pulsar.shade.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at org.apache.pulsar.shade.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at org.apache.pulsar.shade.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at org.apache.pulsar.shade.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at org.apache.pulsar.shade.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at org.apache.pulsar.shade.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

```

cc/ @ivankelly

**Comment by ivankelly** [comment]
@merlimat looking. For future reference, if you link a jenkins build, make sure to click on "Keep this build forever".

**Comment by ivankelly** [comment]
Something weird going on, but not related to s3offload specifically.

It fails when trying to create a ledger handle at 21:19:04.803 [1].

Both bookies have been up since 21:18:30.510 [2][3]. Presumably they've registered in /ledgers/available, but it's impossible to tell without access to the zookeeper transaction log. Perhaps we should pull that out for each test.

The other possibility is that somehow the bookkeeper client's local cache hasn't updated to reflect what is in zookeeper, but this seems unlikely given that 30 seconds have elapsed.

[1] [broker log](https://builds.apache.org/job/pulsar_precommit_integrationtests/1859/artifact/tests/integration/s3-offload/target/container-logs/pulsar-broker1_e004eca2-01ae-49e5-909b-252c956969ee/pulsar-broker.log)
[2] [bookie1 log](https://builds.apache.org/job/pulsar_precommit_integrationtests/1859/artifact/tests/integration/s3-offload/target/container-logs/bookkeeper1_e004eca2-01ae-49e5-909b-252c956969ee/pulsar-bookie.log)
[3] [bookie2 log](https://builds.apache.org/job/pulsar_precommit_integrationtests/1859/artifact/tests/integration/s3-offload/target/container-logs/bookkeeper2_e004eca2-01ae-49e5-909b-252c956969ee/pulsar-bookie.log)

**Comment by sijie** [comment]
it is probably related to apache jenkins environment.
