### ISSUE TITLE
Zookeeper won't start on IPV6  machines - UnknownHostException

### ISSUE THREAD

**Issue by dsambandam** [apache/incubator-pulsar#1949]
#### Expected behavior
Successfully start zookeeprs on a IPV6 configured machine 

#### Actual behavior

Fails to resolve hostname /ip address when starting zookeeper even though nslookup works .

12:50:28.476 [QuorumPeer[myid=3]/0.0.0.0:2181] WARN  org.apache.zookeeper.server.quorum.QuorumCnxManager - Cannot open channel to 2 at election address carocnxoappa9v.nss.vzwnet.com:3888
java.net.UnknownHostException: carocnxoappa9v.com
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:214) ~[?:1.8.0]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403) ~[?:1.8.0]
        at java.net.Socket.connect(Socket.java:666) ~[?:1.8.0]
        at org.apache.zookeeper.server.quorum.QuorumCnxManager.connectOne(QuorumCnxManager.java:562) [org.apache.pulsar-pulsar-zookeeper-2.0.0-rc1-incubating.jar:2.0.0-rc1-incubating]
        at org.apache.zookeeper.server.quorum.QuorumCnxManager.connectAll(QuorumCnxManager.java:614) [org.apache.pulsar-pulsar-zookeeper-2.0.0-rc1-incubating.jar:2.0.0-rc1-incubating]
        at org.apache.zookeeper.server.quorum.FastLeaderElection.lookForLeader(FastLeaderElection.java:843) [org.apache.pulsar-pulsar-zookeeper-2.0.0-rc1-incubating.jar:2.0.0-rc1-incubating]
        at org.apache.zookeeper.server.quorum.QuorumPeer.run(QuorumPeer.java:913) [org.apache.pulsar-pulsar-zookeeper-2.0.0-rc1-incubating.jar:2.0.0-rc1-incubating]
12:50:28.477 [QuorumPeer[myid=3]/0.0.0.0:2181] WARN  org.apache.zookeeper.server.quorum.QuorumPeer - Failed to resolve address: carocnxoappa9v.nss.vzwnet.com
****java.net.UnknownHostException: carocnxoappa9v.nss.vzwnet.com
        at java.net.InetAddress.getAllByName0(InetAddress.java:1418) ~[?:1.8.0]
        at java.net.InetAddress.getAllByName(InetAddress.java:1322) ~[?:1.8.0]
        at java.net.InetAddress.getAllByName(InetAddress.java:1245) ~[?:1.8.0]
        at java.net.InetAddress.getByName(InetAddress.java:1195) ~[?:1.8.0]
        at**** org.apache.zookeeper.server.quorum.QuorumPeer$QuorumServer.recreateSocketAddresses(QuorumPeer.java:166) [org.apache.pulsar-pulsar-zookeeper-2.0.0-rc1-incubating.jar:2.0.0-rc1-incubating]
        at org.apache.zookeeper.server.quorum.QuorumCnxManager.connectOne(QuorumCnxManager.java:595) [org.apache.pulsar-pulsar-zookeeper-2.0.0-rc1-incubating.jar:2.0.0-rc1-incubating]
        at org.apache.zookeeper.server.quorum.QuorumCnxManager.connectAll(QuorumCnxManager.java:614) [org.apache.pulsar-pulsar-zookeeper-2.0.0-rc1-incubating.jar:2.0.0-rc1-incubating]
        at org.apache.zookeeper.server.quorum.FastLeaderElection.lookForLeader(FastLeaderElection.java:843) [org.apache.pulsar-pulsar-zookeeper-2.0.0-rc1-incubating.jar:2.0.0-rc1-incubating]
        at org.apache.zookeeper.server.quorum.QuorumPeer.run(QuorumPeer.java:913) [org.apache.pulsar-pulsar-zookeeper-2.0.0-rc1-incubating.jar:2.0.0-rc1-incubating]

nslookup carocnxoappa9v.com
Server:         2001:xxxx:a06:xxxx:f0:fef:0:yyy
Address:        2001:xxxx:a06:xxxx:f0:fef:0:yyy#53

#### Steps to reproduce

1. Follow the below link for Deploying a ZooKeeper cluster :https://pulsar.incubator.apache.org/docs/latest/deployment/cluster/
2. Start the Zookeeper 
3. Issue : Problem is seen in the logs 
cat /VMB/vmb_install/apache-pulsar-2.0.0-rc1-incubating/logs/pulsar-zookeeper-server.log

#### System configuration
**Pulsar version**: 2.0 
Pulsar 2.0.0-rc1-incubating binary release

**Comment by sijie** [comment]
add "-Djava.net.preferIPv4Stack=true" to the java command opts might help.

**Comment by dsambandam** [comment]
We have only IPV6 address configured in the machine.. Tried java.net.preferIPv6Addresses=true in the Java Options updated as part of pulsar_env.sh but didn't seems to be working ..

**Comment by dsambandam** [comment]
I have overriden the below files to fix the issue 

root@carocnxoappa8v apache-pulsar-2.0.0-rc1-incubating]# grep -r "\-Djava.net.preferIPv6Addresses" .
./bin/pulsar:OPTS="$OPTS -Djute.maxbuffer=10485760 -Djava.net.preferIPv6Addresses=true"
./bin/pulsar-perf:OPTS="$OPTS -Dlog4j.configurationFile=`basename $PULSAR_LOG_CONF` -Djava.net.preferIPv6Addresses=true"
./bin/pulsar-client:OPTS="$OPTS -Djava.net.preferIPv6Addresses=true"
./bin/bookkeeper:OPTS="$OPTS -Djava.net.preferIPv6Addresses=true"
./bin/pulsar-admin:OPTS="$OPTS -Djava.net.preferIPv6Addresses=true"

**Comment by merlimat** [comment]
@dsambandam the original error seems to be a failure to resolve the DNS name `carocnxoappa9v.nss.vzwnet.com`. Can you double check the name can be resolved from the ZK server machine?

**Comment by dsambandam** [comment]
@merlimat after the above changes..it seems to be picking up the right IPv6 address but having issues with sockets now ..debugging further.. 

09:41:38.789 [WorkerSender[myid=2]] WARN  org.apache.zookeeper.server.quorum.QuorumCnxManager - Cannot open channel to 1 at election address carocnxoappa8v.nss.vzwnet.com/2001:xxxx:a06:tttt:f1:fef:0:yyyy:3888
java.net.ConnectException: Connection refused (Connection refused)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:380) ~[?:1.8.0]
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:236) ~[?:1.8.0]
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:218) ~[?:1.8.0]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403) ~[?:1.8.0]
        at java.net.Socket.connect(Socket.java:666) ~[?:1.8.0]
        at org.apache.zookeeper.server.quorum.QuorumCnxManager.connectOne(QuorumCnxManager.java:562) [org.apache.pulsar-pulsar-zookeeper-2.0.0-rc1-incubating.jar:2.0.0-rc1-incubating]
        at org.apache.zookeeper.server.quorum.QuorumCnxManager.toSend(QuorumCnxManager.java:538) [org.apache.pulsar-pulsar-zookeeper-2.0.0-rc1-incubating.jar:2.0.0-rc1-incubating]

**Comment by merlimat** [comment]
can you reach another port on that IPv6 address?

**Comment by dsambandam** [comment]
Yes, I am able to reach now ..I have configured 3 zookeeper in a cluster and connection is successful 

10:58:33.434 [carocnxoappa9v.nss.vzwnet.com/2001:4888:a06:2281:f1:fef:0:c51f:3888] INFO  org.apache.zookeeper.server.quorum.QuorumCnxManager - Received connection request /2001:xxxx:a06:ttttf1:fef:0:yyyy:54119

10:58:33.336 [main] INFO  org.apache.zookeeper.server.quorum.QuorumPeer - Resolved hostname: carocnxoappa10v.nss.vzwnet.com to address: carocnxoappa10v.nss.vzwnet.com/2001:ssss:a06:ffff:f1:fef:0:gggg
10:58:33.336 [main] INFO  org.apache.zookeeper.server.quorum.QuorumPeer - Resolved hostname: carocnxoappa9v.nss.vzwnet.com to address: carocnxoappa9v.nss.vzwnet.com/2001:xxxx:a06:tttt:f1:fef:0:yyyy
10:58:33.336 [main] INFO  org.apache.zookeeper.server.quorum.QuorumPeer - Resolved hostname: carocnxoappa8v.nss.vzwnet.com to address: carocnxoappa8v.nss.vzwnet.com/2001:ssss:a06:hhhh:f1:fef:0:tttt

**Comment by sijie** [comment]
Closed the issue since IPV6 is not supported right now. #954 is tracking for adding the support.

**Comment by yicding** [comment]
> Yes, I am able to reach now ..I have configured 3 zookeeper in a cluster and connection is successful
> 
> 10:58:33.434 [carocnxoappa9v.com/2001:4888:a06:2281:f1:fef:0:c51f:3888] INFO org.apache.zookeeper.server.quorum.QuorumCnxManager - Received connection request /2001:xxxx:a06:ttttf1:fef:0:yyyy:54119
> 
> 10:58:33.336 [main] INFO org.apache.zookeeper.server.quorum.QuorumPeer - Resolved hostname: carocnxoappa10v.com to address: carocnxoappa10v.nss.vzwnet.com/2001:ssss:a06:ffff:f1:fef:0:gggg 10:58:33.336 [main] INFO org.apache.zookeeper.server.quorum.QuorumPeer - Resolved hostname: carocnxoappa9v.com to address: carocnxoappa9v.nss.vzwnet.com/2001:xxxx:a06:tttt:f1:fef:0:yyyy 10:58:33.336 [main] INFO org.apache.zookeeper.server.quorum.QuorumPeer - Resolved hostname: carocnxoappa8v.com to address: carocnxoappa8v.nss.vzwnet.com/2001:ssss:a06:hhhh:f1:fef:0:tttt

Can you share your zookeeper.properties server entries? I could not get zkServer to started with the following config:

server.0=0.0.0.0:2888:3888
server.1=[64:aaaa:bbbb:1000::8]:2888:3888

sh-5.0$ ./zkServer.sh status
/usr/bin/java
ZooKeeper JMX enabled by default
Using config: /var/lib/zookeeper/bin/../conf/zoo.cfg
Client port found: 2181. Client address: localhost. Client SSL: false.
Error contacting service. It is probably not running.
