### ISSUE TITLE
Unable to consume messages from a partition

### ISSUE THREAD

**Issue by bardock** [apache/incubator-pulsar#2013]
We have several shared subscriptions of partitioned topics and we found some cases where a subscription's clients are not receiving messages from a specific partition. If we restart the clients, messages are delivered, the lag is consumed, but a few minutes later the problem with the same partition comes up again.
If we restart the broker that contains the failing partition, the partition is realocated in another broker but the problem persists.
The only workaround that we found was to recreate the subscription (disconnect clients, `pulsar-admin persistent unsubscribe` and reconnect) and then move subscription some minutes back to avoid loosing messages.
Did you come up with this problem before? Is there any permanent solution?
Thanks!

#### System configuration
**Pulsar version (brokers)**: 1.20.0
**Pulsar clients version**: 1.22.0

**Comment by sijie** [comment]
did the problem occur again after you resubscribe?

**Comment by bardock** [comment]
No, it didn't

**Comment by sijie** [comment]
@bardock do you have any logs that you can share to help debugging?

**Comment by sijie** [comment]
@bardock it seems difficult to debug this issue without any logs. it is a bit hard to reproduce the behavior.

**Comment by jiazhai** [comment]
@bardock, Is there a way for us to reproduce it？

**Comment by bardock** [comment]
Sorry for the delay guys.

We faced the same issue past week. 
This time we detected the issue 5 hours later, recreated the subscriptions, but when we moved back 5h the cursor the problem appeared again (clients did not receive messages from partition 4).
We finally decided to restart the entire cluster (bookies and brokers) and recreated the subscriptions. However, we didn't moved back the cursor this time because we realized we prefer to lose messages and start consuming the most recent ones (only for this particular topic).

We found some logs starting at the same time the issue started and they were resolved when we restarted the cluster:

```
2018-07-13 19:05:49,194 - WARN  - [BookKeeperClientWorker-20-1:ManagedCursorImpl$11@958] - [fury/global/0f9b2d5d1c3d495d9081e530b18111a3-notifications-news/persistent/0f9b2d5d1c3d495d9081e530b18111a3-notifications-news-partition-4][f6f49168781f402c99ddfa871bc0e90c-fury-news-sender-android-meli.notifications-providers] Error while replaying entries
```
```
2018-07-13 19:05:49,226 - ERROR - [BookKeeperClientWorker-20-1:PersistentDispatcherMultipleConsumers@399] - [persistent://fury/global/0f9b2d5d1c3d495d9081e530b18111a3-notifications-news/0f9b2d5d1c3d495d9081e530b18111a3-notifications-news-partition-4 / f6f49168781f402c99ddfa871bc0e90c-fury-news-sender-android-meli.notifications-providers] Error reading entries at 1199746:2412 : org.apache.bookkeeper.client.BKException$BKTooManyRequestsException, Read Type Replay - Retrying to read in 15.0 seconds
org.apache.bookkeeper.mledger.ManagedLedgerException: org.apache.bookkeeper.client.BKException$BKTooManyRequestsException
Caused by: org.apache.bookkeeper.client.BKException$BKTooManyRequestsException
	at org.apache.bookkeeper.client.BKException.create(BKException.java:92)
	at org.apache.bookkeeper.mledger.impl.EntryCacheImpl.lambda$asyncReadEntry$1(EntryCacheImpl.java:187)
	at org.apache.bookkeeper.client.PendingReadOp.submitCallback(PendingReadOp.java:430)
	at org.apache.bookkeeper.client.PendingReadOp.access$000(PendingReadOp.java:59)
	at org.apache.bookkeeper.client.PendingReadOp$LedgerEntryRequest.sendNextRead(PendingReadOp.java:171)
	at org.apache.bookkeeper.client.PendingReadOp$LedgerEntryRequest.logErrorAndReattemptRead(PendingReadOp.java:227)
	at org.apache.bookkeeper.client.PendingReadOp.readEntryComplete(PendingReadOp.java:380)
	at org.apache.bookkeeper.proto.PerChannelBookieClient$ReadCompletion.readEntryComplete(PerChannelBookieClient.java:1116)
	at org.apache.bookkeeper.proto.PerChannelBookieClient.handleReadResponse(PerChannelBookieClient.java:1048)
	at org.apache.bookkeeper.proto.PerChannelBookieClient$ReadV2ResponseCallback.safeRun(PerChannelBookieClient.java:908)
	at org.apache.bookkeeper.util.SafeRunnable.run(SafeRunnable.java:31)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:748)
```

An this one starting 10 minutes later:

```
2018-07-13 19:15:28,557 - ERROR - [BookKeeperClientWorker-20-1:PersistentDispatcherMultipleConsumers@399] - [persistent://fury/global/0f9b2d5d1c3d495d9081e530b18111a3-notifications-news/0f9b2d5d1c3d495d9081e530b18111a3-notifications-news-partition-4 / f6f49168781f402c99ddfa871bc0e90c-fury-news-sender-android-meli.notifications-providers] Error reading entries at 1199746:2412 : org.apache.bookkeeper.client.BKException$BKTimeoutException, Read Type Replay - Retrying to read in 56.043 seconds
org.apache.bookkeeper.mledger.ManagedLedgerException: org.apache.bookkeeper.client.BKException$BKTimeoutException
Caused by: org.apache.bookkeeper.client.BKException$BKTimeoutException
	at org.apache.bookkeeper.client.BKException.create(BKException.java:100)
	at org.apache.bookkeeper.mledger.impl.EntryCacheImpl.lambda$asyncReadEntry$1(EntryCacheImpl.java:187)
	at org.apache.bookkeeper.client.PendingReadOp.submitCallback(PendingReadOp.java:430)
	at org.apache.bookkeeper.client.PendingReadOp.access$000(PendingReadOp.java:59)
	at org.apache.bookkeeper.client.PendingReadOp$LedgerEntryRequest.sendNextRead(PendingReadOp.java:171)
	at org.apache.bookkeeper.client.PendingReadOp$LedgerEntryRequest.logErrorAndReattemptRead(PendingReadOp.java:227)
	at org.apache.bookkeeper.client.PendingReadOp.readEntryComplete(PendingReadOp.java:380)
	at org.apache.bookkeeper.proto.PerChannelBookieClient$ReadCompletion.readEntryComplete(PerChannelBookieClient.java:1116)
	at org.apache.bookkeeper.proto.PerChannelBookieClient.handleReadResponse(PerChannelBookieClient.java:1048)
	at org.apache.bookkeeper.proto.PerChannelBookieClient$ReadV2ResponseCallback.safeRun(PerChannelBookieClient.java:908)
	at org.apache.bookkeeper.util.SafeRunnable.run(SafeRunnable.java:31)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:748)
```

Thank you so much for the help!

**Comment by sijie** [comment]
@bardock it seems that bookie throttles the read requests. did you see any increased read traffic from bookkeeper's metrics? it might be worth increasing following settings:

"maxPendingReadRequestsPerThread"

https://github.com/apache/incubator-pulsar/blob/master/conf/bookkeeper.conf#L154

**Comment by bardock** [comment]
@sijie We don't have bookkeeper's metrics. 

This cluster has 9 bookies, and we see that 4 of them were using more CPU than the rest (3 of them were stuck at 13%). When we restarted the cluster, every bookie's CPU went normal.
![screen shot 2018-07-19 at 12 43 10 pm](https://user-images.githubusercontent.com/1980715/42953792-910c4628-8b51-11e8-9bbe-0fc10969c757.png)
The problem with partition-4 of this topic started at 16:05 (GMT -3).

So we believe these bookies were performing poorly and caused the throttling. Sadly, we don't have a jstack for that moment. 
Is there anything we can tune up or monitor to prevent this issue? Here is our [config file](https://github.com/apache/incubator-pulsar/files/2210966/bookkeeper.conf.txt).

We are using bk 4.7.0 (shipped with pulsar 2.0.0-rc1) but we are planning to upgrade to 4.7.1.

Thanks!

**Comment by bardock** [comment]
@sijie any thoughts?
We are now using version 4.7.1 and we are tracking almost every bookkeeper metric.
What metrics do you think will be useful to debug this issue?
