### ISSUE TITLE
Initialization of cluster meta data fails while setting up a multi cluster pulsar instance 

### ISSUE THREAD

**Issue by dsambandam** [apache/incubator-pulsar#2037]
Initialization of cluster meta data fails while setting up a multi cluster pulsar instance 

#### Actual behavior
Exception in thread "main" org.apache.zookeeper.KeeperException$NodeExistsException: KeeperErrorCode = NodeExists for /managed-ledgers
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:119)
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
        at org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:783)
        at org.apache.pulsar.PulsarClusterMetadataSetup.main(PulsarClusterMetadataSetup.java:139)

#### Steps to reproduce
1. Setup Cluster-A ( Deploy Zookeepers)
2. Initialize Cluster-A Meta Data
3. Setup Cluster-B (Deploy Zookeepers)
4. Initialize Cluster-B Meta data 

Result : Meta data setup fails with the above error .
Any suggestions to resolve the problem?

How can we reproduce the issue

#### System configuration
**Pulsar version**: 2.0

**Comment by dsambandam** [comment]
Any suggestions on how to start global-zookeeper in the foreground since Pulsar daemon process fails to start on the same node in which local zookeeper is deployed with no logs? Hope global and local zookeeper are started on different ports..Please confirm.

Pulsar script doesn't seem to support in FG

00:10:49.088 [main] ERROR org.apache.zookeeper.server.ZooKeeperServerMain - Invalid arguments, exiting abnormally
java.lang.IllegalArgumentException: Invalid number of arguments:[]
        at org.apache.zookeeper.server.ServerConfig.parse(ServerConfig.java:56) ~[org.apache.pulsar-pulsar-zookeeper-2.0.0-rc1-incubating.jar:2.0.0-rc1-incubating]
        at org.apache.zookeeper.server.ZooKeeperServerMain.initializeAndRun(ZooKeeperServerMain.java:84) ~[org.apache.pulsar-pulsar-zookeeper-2.0.0-rc1-incubating.jar:2.0.0-rc1-incubating]
        at org.apache.zookeeper.server.ZooKeeperServerMain.main(ZooKeeperServerMain.java:53) [org.apache.pulsar-pulsar-zookeeper-2.0.0-rc1-incubating.jar:2.0.0-rc1-incubating]
        at org.apache.zookeeper.server.quorum.QuorumPeerMain.initializeAndRun(QuorumPeerMain.java:116) [org.apache.pulsar-pulsar-zookeeper-2.0.0-rc1-incubating.jar:2.0.0-rc1-incubating]
        at org.apache.zookeeper.server.quorum.QuorumPeerMain.main(QuorumPeerMain.java:78) [org.apache.pulsar-pulsar-zookeeper-2.0.0-rc1-incubating.jar:2.0.0-rc1-incubating]
        at org.apache.pulsar.zookeeper.ZooKeeperStarter.start(ZooKeeperStarter.java:68) [org.apache.pulsar-pulsar-zookeeper-2.0.0-rc1-incubating.jar:2.0.0-rc1-incubating]
        at org.apache.pulsar.zookeeper.ConfigurationStoreStarter.main(ConfigurationStoreStarter.java:26) [org.apache.pulsar-pulsar-zookeeper-2.0.0-rc1-incubating.jar:2.0.0-rc1-incubating]
00:10:49.091 [main] INFO  org.apache.zookeeper.server.ZooKeeperServerMain - Usage: ZooKeeperServerMain configfile | port datadir [ticktime] [maxcnxns]

**Comment by sijie** [comment]
> Exception in thread "main" org.apache.zookeeper.KeeperException$NodeExistsException: 

Are you sharing same nodes for zookeeper for both cluster A and B?

> Any suggestions on how to start global-zookeeper in the foreground since Pulsar daemon process fails to start on the same node in which local zookeeper is deployed with no logs? 

you can run `bin/pulsar global-zookeeper`.

**Comment by dsambandam** [comment]
Different nodes for Cluster A and B . 

bin/pulsar global-zookeeper doesn't work..it fails with the above error 

00:10:49.088 [main] ERROR org.apache.zookeeper.server.ZooKeeperServerMain - Invalid arguments, exiting abnormally
java.lang.IllegalArgumentException: Invalid number of arguments:[]

**Comment by sijie** [comment]
sorry for late response. @dsambandam do you mind providing me the list of commands you are invoking? so I can try to reproduce it.

**Comment by sijie** [comment]
@dsambandam any more information?

**Comment by sijie** [comment]
It seems no updates here. I will close this for now. If there are more instructions on how to reproduce it,  open an issue for that, we will investigate the issue.

**Comment by dsambandam** [comment]
Apologies for the delays and I was travelling last week. We can close this ticket as I was able to initialize metadata ..

**Comment by dsambandam** [comment]
Still having issues starting global zookeeper, so created a ticket to track the same.

**Comment by Audace** [comment]
@dsambandam how did you resolve this issue?
