### ISSUE TITLE
'java.lang.NoSuchMethodError' when running standalone

### ISSUE THREAD

**Issue by djKooks** [apache/incubator-pulsar#2166]
Hello,
I just started to run on `bin/pulsar standalone` after maven build, but it shows some problem.
Does someone knows about this?

Thanks.

#### Expected behavior
Standalone server goes on.

#### Actual behavior
```
$ bin/pulsar standalone
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/kwangin/utils/apache-hive/lib/log4j-slf4j-impl-2.6.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/kwangin/.m2/repository/org/apache/logging/log4j/log4j-slf4j-impl/2.10.0/log4j-slf4j-impl-2.10.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
Exception in thread "main" java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.util.EnumResolver.constructUsingToString(Ljava/lang/Class;Lcom/fasterxml/jackson/databind/AnnotationIntrospector;)Lcom/fasterxml/jackson/databind/util/EnumResolver;
	at org.apache.pulsar.common.util.FieldParser.convert(FieldParser.java:98)
	at org.apache.pulsar.common.util.FieldParser.value(FieldParser.java:170)
	at org.apache.pulsar.common.util.FieldParser.lambda$update$0(FieldParser.java:137)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at org.apache.pulsar.common.util.FieldParser.update(FieldParser.java:133)
	at org.apache.pulsar.common.configuration.PulsarConfigurationLoader.create(PulsarConfigurationLoader.java:89)
	at org.apache.pulsar.common.configuration.PulsarConfigurationLoader.create(PulsarConfigurationLoader.java:73)
	at org.apache.pulsar.PulsarStandaloneStarter.<init>(PulsarStandaloneStarter.java:58)
	at org.apache.pulsar.PulsarStandaloneStarter.main(PulsarStandaloneStarter.java:101)

```

#### Steps to reproduce
```
$ mvn install -DskipTests
$ bin/pulsar standalone
```

#### System configuration
Newest master branch

**Comment by srkukarni** [comment]
I built master and did not encounter any such issue. What's your os/java version?

**Comment by djKooks** [comment]
@srkukarni It is MacOS(with Java8). Is MacOS not supported?

**Comment by srkukarni** [comment]
Mac is supported and I tried on mac as well.
Can you see if you can wipe your ~/.m2/repository and then try again?

**Comment by merlimat** [comment]
@djKooks one other thing that might help is to do `mvn clean` and try again. I've seen sometimes a double `mvn install` will leave the target directories in a weird state.

**Comment by djKooks** [comment]
@srkukarni @merlimat seems working. Thanks for help!
