### ISSUE TITLE
Intermittent test failures in ProxyPublishConsumeTest. socketTest

### ISSUE THREAD

**Issue by merlimat** [apache/incubator-pulsar#237]
```
socketTest(com.yahoo.pulsar.websocket.proxy.ProxyPublishConsumeTest)  Time elapsed: 30.018 sec  <<< FAILURE!
org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.socketTest() didn't finish within the time-out 30000
	at com.yahoo.pulsar.websocket.proxy.ProxyPublishConsumeTest.socketTest(ProxyPublishConsumeTest.java:103)
```

**Comment by merlimat** [comment]
@jai1 Test is still failing with timeout https://travis-ci.org/yahoo/pulsar/builds/205425873

```
socketTest(com.yahoo.pulsar.websocket.proxy.ProxyPublishConsumeTest)  Time elapsed: 30.017 sec  <<< FAILURE!
org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.socketTest() didn't finish within the time-out 30000
	at com.yahoo.pulsar.websocket.proxy.ProxyPublishConsumeTest.socketTest(ProxyPublishConsumeTest.java:105)
```

The thread is blocked at line 105:

```java
                consumeClient.stop();
```

**Comment by merlimat** [comment]
Fixed in #253

**Comment by merlimat** [comment]
Tests are still failing in master : 

```
socketTest(com.yahoo.pulsar.websocket.proxy.ProxyPublishConsumeTest)  Time elapsed: 10.026 sec  <<< FAILURE!
org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.socketTest() didn't finish within the time-out 10000
	at com.yahoo.pulsar.websocket.proxy.ProxyPublishConsumeTest.socketTest(ProxyPublishConsumeTest.java:110)

```

**Comment by merlimat** [comment]
@joefk  @rdhabalia Found out the reasons this test is failing, will submit a PR shortly

**Comment by sijie** [comment]
This is fixed by multiple PRs referenced here.
