### ISSUE TITLE
Intermittent test failure: Websocket.LookupProtocolTest

### ISSUE THREAD

**Issue by rdhabalia** [apache/incubator-pulsar#578]
Intermittent test failure of [Websocket.LookupProtocolTest](https://github.com/apache/incubator-pulsar/blob/master/pulsar-websocket/src/test/java/org/apache/pulsar/websocket/LookupProtocolTest.java)

```
Running TestSuite
Tests run: 6, Failures: 4, Errors: 0, Skipped: 0, Time elapsed: 40.726 sec <<< FAILURE! - in TestSuite
binaryLookupTest(org.apache.pulsar.websocket.LookupProtocolTest)  Time elapsed: 10.009 sec  <<< FAILURE!
org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.binaryLookupTest() didn't finish within the time-out 10000
	at org.apache.pulsar.websocket.LookupProtocolTest.binaryLookupTest(LookupProtocolTest.java:68)

binaryTlsLookupTest(org.apache.pulsar.websocket.LookupProtocolTest)  Time elapsed: 10.002 sec  <<< FAILURE!
org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.binaryTlsLookupTest() didn't finish within the time-out 10000
	at org.apache.pulsar.websocket.LookupProtocolTest.binaryTlsLookupTest(LookupProtocolTest.java:85)

httpLookupTest(org.apache.pulsar.websocket.LookupProtocolTest)  Time elapsed: 10.001 sec  <<< FAILURE!
org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.httpLookupTest() didn't finish within the time-out 10000
	at org.apache.pulsar.websocket.LookupProtocolTest.httpLookupTest(LookupProtocolTest.java:36)

httpsLookupTest(org.apache.pulsar.websocket.LookupProtocolTest)  Time elapsed: 10.006 sec  <<< FAILURE!
org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.httpsLookupTest() didn't finish within the time-out 10000
	at org.apache.pulsar.websocket.LookupProtocolTest.httpsLookupTest(LookupProtocolTest.java:52)


Results :

Failed tests: 
  LookupProtocolTest.binaryLookupTest:68 » ThreadTimeout Method org.testng.inter...
  LookupProtocolTest.binaryTlsLookupTest:85 » ThreadTimeout Method org.testng.in...
  LookupProtocolTest.httpLookupTest:36 » ThreadTimeout Method org.testng.interna...
  LookupProtocolTest.httpsLookupTest:52 » ThreadTimeout Method org.testng.intern...
```

**Comment by merlimat** [comment]
Yes, saw that multiple times. Cannot reproduce locally.. 

in all the tests, it seems blocked on the line : 

```java
        PulsarClientImpl testClient = (PulsarClientImpl) service.getPulsarClient();
```

**Comment by rdhabalia** [comment]
yes, recently all the builds are failing on this test case. 

>in all the tests, it seems blocked on the line :

yes, thread is stuck while creating `PulsarClientImpl` but don't see a clear reason, looking into it.

**Comment by merlimat** [comment]
Not necessarily creating the `PulsarClientImpl` instance. It could also be the line: 

```java
// If not explicitly set, read clusters data from ZK
localCluster = retrieveClusterData();
```

**Comment by merlimat** [comment]
`WebSocketService.java:169`

**Comment by rdhabalia** [comment]
[WebSocketService](https://github.com/apache/incubator-pulsar/blob/master/pulsar-websocket/src/main/java/org/apache/pulsar/websocket/WebSocketService.java#L85) creates `localCluster` on service init so, in this test-case, it should not be null.

**Comment by rdhabalia** [comment]
it seems it's a deadlock while loading runtime library.
`Epoll.isAvailable()` tries to load library and that thread is in RUNNABLE state which is holding a lock required by other thread.

```
"pulsar-websocket-1-1" #21 prio=5 os_prio=0 tid=0x00007f3988841800 nid=0x3eee waiting for monitor entry [0x00007f396984f000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at java.lang.Runtime.loadLibrary0(Runtime.java:862)
        - waiting to lock <0x00000000d7686230> (a java.lang.Runtime)
        at java.lang.System.loadLibrary(System.java:1122)
        at sun.nio.ch.IOUtil$1.run(IOUtil.java:359)
        at sun.nio.ch.IOUtil$1.run(IOUtil.java:357)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.nio.ch.IOUtil.<clinit>(IOUtil.java:356)
        at sun.nio.ch.FileChannelImpl.<clinit>(FileChannelImpl.java:1224)
        at sun.management.ManagementFactoryHelper.getBufferPoolMXBeans(ManagementFactoryHelper.java:214)
        - locked <0x00000000d6804528> (a java.lang.Class for sun.management.ManagementFactoryHelper)
        at java.lang.management.PlatformComponent$11.getMXBeans(PlatformComponent.java:215)
        at java.lang.management.PlatformComponent.getMXBeans(PlatformComponent.java:377)
        at java.lang.management.ManagementFactory.getPlatformMBeanServer(ManagementFactory.java:472)
        - locked <0x00000000d67e9970> (a java.lang.Class for java.lang.management.ManagementFactory)
        at org.apache.pulsar.websocket.stats.JvmMetrics.updateGcStats(JvmMetrics.java:119)
        at org.apache.pulsar.websocket.stats.JvmMetrics$$Lambda$1/1568059495.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
        at java.lang.Thread.run(Thread.java:745)




"main" #1 prio=5 os_prio=0 tid=0x00007f3988008800 nid=0x3ecf in Object.wait() [0x00007f398f639000]
   java.lang.Thread.State: RUNNABLE
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
        - locked <0x00000000d7633588> (a java.util.Vector)
        - locked <0x00000000d76b4af0> (a java.util.Vector)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
        at java.lang.Runtime.load0(Runtime.java:809)
        - locked <0x00000000d7686230> (a java.lang.Runtime)
        at java.lang.System.load(System.java:1086)
        at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:36)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:272)
        at java.security.AccessController.doPrivileged(Native Method)
        at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:264)
        at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:252)
        at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:226)
        at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:269)
        at io.netty.channel.epoll.Native.<clinit>(Native.java:64)
        at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:33)
        at org.apache.pulsar.common.util.netty.EventLoopUtil.newEventLoopGroup(EventLoopUtil.java:43)
        at org.apache.pulsar.client.impl.PulsarClientImpl.getEventLoopGroup(PulsarClientImpl.java:469)
        at org.apache.pulsar.client.impl.PulsarClientImpl.<init>(PulsarClientImpl.java:84)
        at org.apache.pulsar.client.api.PulsarClient.create(PulsarClient.java:58)
        at org.apache.pulsar.websocket.WebSocketService.createClientInstance(WebSocketService.java:197)
        at org.apache.pulsar.websocket.WebSocketService.getPulsarClient(WebSocketService.java:171)
        - locked <0x00000000d655a020> (a org.apache.pulsar.websocket.WebSocketService)
        at org.apache.pulsar.websocket.LookupProtocolTest.binaryLookupTest(LookupProtocolTest.java:68)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
        at org.testng.TestRunner.privateRun(TestRunner.java:767)
        at org.testng.TestRunner.run(TestRunner.java:617)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
        at org.testng.SuiteRunner.run(SuiteRunner.java:240)
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
        at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
        at org.testng.TestNG.run(TestNG.java:1057)
        at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:132)
        at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
        at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
        at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:147)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)

```

**Comment by rdhabalia** [comment]
[full jsatck](https://gist.github.com/rdhabalia/5d9d5053b19807ab4b91614bf1c1038f)
