### ISSUE TITLE
Intermittent test failure on NonPersistentTopicTest

### ISSUE THREAD

**Issue by merlimat** [apache/incubator-pulsar#612]
Seen at 
https://builds.apache.org/job/pulsar-pull-request/org.apache.pulsar$pulsar-broker/11/testReport/junit/org.apache.pulsar.client.api/NonPersistentTopicTest/testProducerRateLimit/

```
java.lang.AssertionError: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertFalse(Assert.java:63)
	at org.testng.Assert.assertFalse(Assert.java:73)
	at org.apache.pulsar.client.api.NonPersistentTopicTest.testProducerRateLimit(NonPersistentTopicTest.java:284)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by merlimat** [comment]
This one is reproducible locally. There is an exception in the `sendAsync()` : 

```
java.util.concurrent.TimeoutException
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1771)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
	at org.apache.pulsar.client.api.NonPersistentTopicTest.lambda$0(NonPersistentTopicTest.java:263)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by merlimat** [comment]
It's because the 1sec timeout is sometimes too short. I have a fix for this
