### ISSUE TITLE
Intermittent test failures in AdminApiTest.testIncrementPartitionsOfTopic

### ISSUE THREAD

**Issue by merlimat** [apache/incubator-pulsar#635]
As seen in https://builds.apache.org/job/pulsar-pull-request/org.apache.pulsar$pulsar-broker/59/testReport/junit/org.apache.pulsar.broker.admin/AdminApiTest/testIncrementPartitionsOfTopic/

```
java.lang.AssertionError: expected [8] but found [12]
	at org.apache.pulsar.broker.admin.AdminApiTest.testIncrementPartitionsOfTopic(AdminApiTest.java:1761)
```

Apparently, this failure is causing other tests in `AdminApiTests` to fail afterwards:

```
org.apache.pulsar.broker.admin.AdminApiTest.testIncrementPartitionsOfTopic
org.apache.pulsar.broker.admin.AdminApiTest.testIncrementPartitionsOfTopic
org.apache.pulsar.broker.admin.AdminApiTest.testNamespaceSplitBundle
org.apache.pulsar.broker.admin.AdminApiTest.testNamespaceUnloadBundle
org.apache.pulsar.broker.admin.AdminApiTest.testPersistentTopicsExpireMessages
org.apache.pulsar.broker.admin.AdminApiTest.testPulsarAdminForUriAndUrlEncoding
org.apache.pulsar.broker.admin.AdminApiTest.testPulsarAdminForUriAndUrlEncoding
```

**Comment by merlimat** [comment]
@rdhabalia Do you have any suspect on this one?

**Comment by merlimat** [comment]
@rdhabalia Looks like it failed again in https://builds.apache.org/job/pulsar-master/org.apache.pulsar$pulsar-broker/15/testReport/junit/org.apache.pulsar.broker.admin/AdminApiTest/testIncrementPartitionsOfTopic/

**Comment by rdhabalia** [comment]
It seems it is not the same `assert-failure` but it failed with 500 due to `PulsarService` gets shutdown in between the test and while running the test I can see exception:
```
org.apache.pulsar.broker.service.BrokerServiceException$PersistenceException: org.apache.bookkeeper.mledger.ManagedLedgerException: ManagedLedger prop-xyz/use/ns1/persistent/topic_%2B%26*%25%7B%7D%28%29+%5C%2F%24%40%23%5E%25-partition-5 has already been closed
```
I can also see that `BatchMessageTest. testBatchAndNonBatchCumulativeAcks` runs on the same process and it might be closing pulsar-service. 

Checking what exactly happened..

**Comment by merlimat** [comment]
Still happens on current master: 

https://builds.apache.org/job/pulsar-master/org.apache.pulsar$pulsar-broker/31/testReport/junit/org.apache.pulsar.broker.admin/AdminApiTest/testIncrementPartitionsOfTopic/

```
Error Message

expected [8] but found [12]
Stacktrace

java.lang.AssertionError: expected [8] but found [12]
	at org.apache.pulsar.broker.admin.AdminApiTest.testIncrementPartitionsOfTopic(AdminApiTest.java:1765)
```

**Comment by rdhabalia** [comment]
Actually, even in last build, test is not failed due to assertion error but it failed with 500-error because broker gets shutdown during the test and topic is closed.

```
persistent://prop-xyz/use/ns1/topic_+&*%{}() \/$@#^%
org.apache.pulsar.broker.service.BrokerServiceException$PersistenceException: org.apache.bookkeeper.mledger.ManagedLedgerException: ManagedLedger prop-xyz/use/ns1/persistent/topic_%2B%26*%25%7B%7D%28%29+%5C%2F%24%40%23%5E%25-partition-4 has already been closed
	at org.apache.pulsar.broker.service.persistent.PersistentTopic$2.openCursorFailed(PersistentTopic.java:456)
	at org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl.asyncOpenCursor(ManagedLedgerImpl.java:584)
	at org.apache.pulsar.broker.service.persistent.PersistentTopic.getDurableSubscription(PersistentTopic.java:441)
	at org.apache.pulsar.broker.service.persistent.PersistentTopic.createSubscription(PersistentTopic.java:494)
	at org.apache.pulsar.broker.admin.PersistentTopics$3.lambda$2(PersistentTopics.java:1322)
	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:822)
	at java.util.concurrent.CompletableFuture.uniHandleStage(CompletableFuture.java:834)
	at java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:2155)
	at org.apache.pulsar.broker.admin.PersistentTopics$3.lambda$0(PersistentTopics.java:1316)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.apache.pulsar.broker.admin.PersistentTopics$3.operationComplete(PersistentTopics 
```

`AdminApitTest` creates 2 pulsar instance and shutdown and `testIncrementPartitionsOfTopic` runs twice with different topic name. and according to log: broker shutdowns while test is running second time. 
```
486298 [main] INFO org.apache.pulsar.broker.service.BrokerService - Shutting down Pulsar Broker service
486298 [main] INFO org.apache.pulsar.zookeeper.ZooKeeperDataCache - [MockZookeeper] Received ZooKeeper watch event: WatchedEvent state:SyncConnected type:NodeDeleted path:/loadbalance/brokers/localhost:15413
```

So, created #676 , and hopefully it should fix it.

**Comment by merlimat** [comment]
Still seing the test failure with "internal server error" on broker side for topic being closed: 

https://builds.apache.org/job/pulsar-master/org.apache.pulsar$pulsar-broker/82/testReport/junit/org.apache.pulsar.broker.admin/AdminApiTest/testIncrementPartitionsOfTopic/


```
https://builds.apache.org/job/pulsar-master/org.apache.pulsar$pulsar-broker/82/testReport/junit/org.apache.pulsar.broker.admin/AdminApiTest/testIncrementPartitionsOfTopic/
```

**Comment by rdhabalia** [comment]
#778 will fix this issue. so, closing this issue.
