### ISSUE TITLE
split-bundle: lookup failure + error logs of split-bundle

### ISSUE THREAD

**Issue by rdhabalia** [apache/incubator-pulsar#821]
#### Expected behavior

When broker splits bundle then other broker which receives lookup-request for a topic which falls under that bundle should be redirected properly.

#### Actual behavior

Right now, as described at [in the mail](https://lists.apache.org/thread.html/c82e5f7d239468a3f1b02d61e15632abf63f47867b8e1b9611628d0c@%3Cusers.pulsar.apache.org%3E), there are two issues:

**1. Lookup fails after bundle-split**
```
Caused by: java.util.concurrent.CompletionException: org.apache.pulsar.client.api.PulsarClientException$LookupException: java.lang.IllegalStateException: Namespace bundle test/us-west/ns-bundle/0x50000000_0x60000000 is being unloaded
```
It happens in following scenario: 
1. Broker-2 receives a lookup request for a brand-new namespace (which doesn't have local-policies), so, broker-2 creates local-policies, puts bundle data into `bundlesCache`, and assigns bundle to Broker-1.
2. Now,  Broker-1 splits bundle, disable original bundle and updates local-policies.
3. Broker-2 doesn't know about newly split bundle and original bundle is disable. So, any lookup request for this bundle on broker-2 will receive above error.

**2. Split-bundle fails**

```
2017-10-11 18:19:07,975 - INFO  [pulsar-web-56-3:Namespaces@789] - [null] Split namespace bundle test/us-west/ns-bundle/0x50000000_0x58000000
2017-10-11 18:19:07,976 - INFO  [pulsar-web-56-3:PulsarWebResource@222] - Successfully validated clusters on property [test]
2017-10-11 18:19:07,976 - ERROR [pulsar-web-56-3:PulsarWebResource@373] - [null] Failed to validate namespace bundle test/us-west/ns-bundle/0x50000000_0x58000000
java.lang.IllegalArgumentException: Invalid upper boundary for bundle
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:93)
	at org.apache.pulsar.common.naming.NamespaceBundles.validateBundle(NamespaceBundles.java:110)
	at org.apache.pulsar.broker.web.PulsarWebResource.validateNamespaceBundleRange(PulsarWebResource.java:370)
	at org.apache.pulsar.broker.web.PulsarWebResource.validateNamespaceBundleOwnership(PulsarWebResource.java:381)
	at org.apache.pulsar.broker.admin.Namespaces.splitNamespaceBundle(Namespaces.java:801)
```

This issue happens due to stale data into LoadBalancer and it tries to split already split bundle. So, it  doesn't have any functional issue and it would be resolved after a minute as soon as load-manager will get latest data. So, to fix it: load-balancer should get latest data after bundle-split. After reproducing, I am seeing below logs
```
// (1) Load-balancer selected bundle to split
20:26:57.438 [pulsar-load-manager-11-1] INFO  o.a.p.b.l.impl.SimpleLoadManagerImpl - Will split hot namespace bundle cms-java-systest/perf/part-bundle2/0x78000000_0x80000000, topics 2, producers+consumers 2, msgRate in+out 3753.588550254447, bandwidth in+out 3967543.0976189505
// (2) Split is successful
20:26:57.525 [pulsar-web-72-11] INFO  o.a.pulsar.broker.admin.Namespaces   -  Split namespace bundle cms-java-systest/perf/part-bundle2/0x78000000_0x80000000
20:26:57.545 [pulsar-load-manager-11-1] INFO  o.a.p.b.l.impl.SimpleLoadManagerImpl - Successfully split namespace bundle cms-java-systest/perf/part-bundle2/0x78000000_0x80000000

// (3) Again Load-balancer selected same bundle to split with same old data. and it fails while splitiing 
20:27:02.396 [pulsar-load-manager-11-1] INFO  o.a.p.b.l.impl.SimpleLoadManagerImpl - Will split hot namespace bundle cms-java-systest/perf/part-bundle2/0x78000000_0x80000000, topics 2, producers+consumers 2, msgRate in+out 3753.588550254447, bandwidth in+out 3967543.0976189505
20:27:02.396 [pulsar-simple-load-manager-70-1] INFO  o.a.p.b.l.impl.SimpleLoadManagerImpl - doLoadRanking - load balancing strategy: weightedRandomSelection
20:27:02.468 [pulsar-web-72-15] INFO  o.a.pulsar.broker.admin.Namespaces   - Split namespace bundle cms-java-systest/perf/part-bundle2/0x78000000_0x80000000
20:27:02.469 [pulsar-web-72-15] INFO  o.a.p.broker.web.PulsarWebResource   - Successfully validated clusters on property [cms-java-systest]
20:27:02.470 [pulsar-web-72-15] ERROR o.a.p.broker.web.PulsarWebResource   - Failed to validate namespace bundle cms-java-systest/perf-gq1/part-bundle2/0x78000000_0x80000000
java.lang.IllegalArgumentException: Invalid upper boundary for bundle
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:93) ~[guava-15.0.jar:na]
        at org.apache.pulsar.common.naming.NamespaceBundles.validateBundle(NamespaceBundles.java:110) ~[pulsar-broker-1.20.0-incubating-yahoo.jar:1.20.0-incubating-yahoo]
        at org.apache.pulsar.broker.web.PulsarWebResource.validateNamespaceBundleRange(PulsarWebResource.java:369) [pulsar-broker-1.20.0-incubating-yahoo.jar:1.20.0-incubating-yahoo]
        at org.apache.pulsar.broker.web.PulsarWebResource.validateNamespaceBundleOwnership(PulsarWebResource.java:395) [pulsar-broker-1.20.0-incubating-yahoo.jar:1.20.0-incubating-yahoo]
        at org.apache.pulsar.broker.admin.Namespaces.splitNamespaceBundle(Namespaces.java:854) [pulsar-broker-1.20.0-incubating-yahoo.jar:1.20.0-incubating-yahoo]
        at sun.reflect.GeneratedMethodAccessor115.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]


```

I will create 2 PR with the fix.

**Comment by merlimat** [comment]
The 2 fixes have been merged
