### ISSUE TITLE
Intermittent test failure in NonPersistentTopicTest.testMsgDropStat

### ISSUE THREAD

**Issue by merlimat** [apache/incubator-pulsar#867]
```
Error Message

Index: 0, Size: 0

Stacktrace

java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at org.apache.pulsar.client.api.NonPersistentTopicTest.testMsgDropStat(NonPersistentTopicTest.java:764)
```

https://builds.apache.org/job/pulsar-pull-request/org.apache.pulsar$pulsar-broker/641/testReport/junit/org.apache.pulsar.client.api/NonPersistentTopicTest/testMsgDropStat/

**Comment by rdhabalia** [comment]
will look into it.
